#!/usr/bin/env bash
set -e
__version=0.0.1
which ralode moonwalk mpv > /dev/null

while getopts vh opt; do
    case "$opt" in
        v) echo Version: $__version; exit 0;;
        h) echo "Usage: $0 -h|-v|<url>"; exit 0;;
    esac
done

__url=$(ralode "$1" || moonwalk "$1")
(set -m; exec mpv "$__url" &)
