#!/usr/bin/env bash
set -e
which http ag jq xmllint fzf rootname > /dev/null

__json=`http "$1" | ag -o "RalodePlayer.init\(\K{.*}(?=\))"`
__json=`sed -e '1s/^/[/' -e '$s/$/]/' <<< "$__json"`
__name=`jq -r '.[0] | .[] | .name' <<< "$__json" | fzf --prompt="Select a dubber: "`

declare -A __items
eval $(jq -r '.[0] | .[] | select(.name == "'"$__name"'") | .items[] | "__items[\"" + .sname + "\"]=" + (.scode | capture("src=(?<a>\"[^\"]+\")") | .a)' <<< "$__json")

__series=`printf "%s\n" "${!__items[@]}" | sort -V | fzf --no-sort --tac --prompt="Select a series: "`
http "$(rootname "$1")${__items["$__series"]}" | xmllint --html --xpath "string(//iframe/@src)" - 2>/dev/null | sed 's@^//@http://@'
